"""Deterministic shell completion generated from an argparse parser."""

from __future__ import annotations

import argparse
import shlex


_CommandNode = tuple[list[str], list[str], list[str]]


def _command_tree(parser: argparse.ArgumentParser) -> dict[tuple[str, ...], _CommandNode]:
    tree: dict[tuple[str, ...], _CommandNode] = {}

    def visit(current: argparse.ArgumentParser, path: tuple[str, ...]) -> None:
        options = sorted({
            option
            for action in current._actions
            for option in action.option_strings
        })
        value_options = sorted(
            {
                option
                for action in current._actions
                if action.nargs != 0
                for option in action.option_strings
            }
        )
        children: dict[str, argparse.ArgumentParser] = {}
        for action in current._actions:
            if isinstance(action, argparse._SubParsersAction):
                children.update(action.choices)
        tree[path] = (sorted(children), options, value_options)
        for name, child in sorted(children.items()):
            visit(child, path + (name,))

    visit(parser, ())
    return tree


def _path_cases(
    tree: dict[tuple[str, ...], _CommandNode],
    *,
    value_options: bool,
) -> list[str]:
    cases: list[str] = []
    for path, (commands, _, options_with_values) in sorted(tree.items()):
        key = " ".join(path)
        words = options_with_values if value_options else commands
        for word in words:
            pattern = shlex.quote(f"{key}:{word}")
            if value_options:
                cases.append(f"      {pattern}) skip_next=1; continue ;;")
            else:
                new_path = shlex.quote(" ".join(path + (word,)))
                cases.append(f"      {pattern}) path={new_path} ;;")
    return cases


def _fish_path_cases(
    tree: dict[tuple[str, ...], _CommandNode],
    *,
    value_options: bool,
) -> list[str]:
    cases: list[str] = []
    for path, (commands, _, options_with_values) in sorted(tree.items()):
        key = " ".join(path)
        words = options_with_values if value_options else commands
        for word in words:
            cases.append(f"      case {shlex.quote(f'{key}:{word}')}")
            if value_options:
                cases.extend(("        set skip_next 1", "        continue"))
            else:
                cases.append(
                    f"        set path {shlex.quote(' '.join(path + (word,)))}"
                )
    return cases


def generate_completion(parser: argparse.ArgumentParser, shell: str) -> str:
    """Return a completion program for bash, zsh, or fish."""
    tree = _command_tree(parser)
    if shell == "bash":
        cases = []
        for path, (commands, options, _) in sorted(tree.items()):
            key = " ".join(path)
            words = " ".join(commands + options)
            cases.append(f"    {shlex.quote(key)}) choices={shlex.quote(words)} ;;")
        return "\n".join([
            "# generated by config-cli; do not edit",
            "_config_cli_complete() {",
            "  local cur path choices word i skip_next",
            "  cur=${COMP_WORDS[COMP_CWORD]}",
            "  path=",
            "  skip_next=0",
            "  for ((i=1; i<COMP_CWORD; i++)); do",
            "    word=${COMP_WORDS[i]}",
            "    if ((skip_next)); then",
            "      skip_next=0",
            "      continue",
            "    fi",
            "    [[ $word == --*=* ]] && continue",
            "    case \"$path:$word\" in",
            *_path_cases(tree, value_options=True),
            "    esac",
            "    case \"$path:$word\" in",
            *_path_cases(tree, value_options=False),
            "    esac",
            "  done",
            "  if ((skip_next)); then",
            "    COMPREPLY=()",
            "    return",
            "  fi",
            "  case \"$path\" in",
            *cases,
            "    *) choices='' ;;",
            "  esac",
            "  COMPREPLY=( $(compgen -W \"$choices\" -- \"$cur\") )",
            "}",
            "complete -F _config_cli_complete config-cli",
            "",
        ])
    if shell == "zsh":
        cases = []
        for path, (commands, options, _) in sorted(tree.items()):
            key = " ".join(path)
            words = " ".join(commands + options)
            cases.extend((f"    {shlex.quote(key)})", f"      _values 'config-cli' {words} ;;"))
        return "\n".join([
            "#compdef config-cli",
            "# generated by config-cli; do not edit",
            "_config_cli() {",
            "  local path='' word",
            "  integer skip_next=0",
            "  for word in ${words[2,CURRENT-1]}; do",
            "    if ((skip_next)); then",
            "      skip_next=0",
            "      continue",
            "    fi",
            "    [[ $word == --*=* ]] && continue",
            "    case \"$path:$word\" in",
            *_path_cases(tree, value_options=True),
            "    esac",
            "    case \"$path:$word\" in",
            *_path_cases(tree, value_options=False),
            "    esac",
            "  done",
            "  ((skip_next)) && return 0",
            "  case $path in",
            *cases,
            "  esac",
            "}",
            "compdef _config_cli config-cli",
            "",
        ])
    if shell == "fish":
        lines = [
            "# generated by config-cli; do not edit",
            "function __config_cli_path_is",
            "  set -l tokens (commandline -opc)",
            "  set -e tokens[1]",
            "  set -l path ''",
            "  set -l skip_next 0",
            "  for word in $tokens",
            "    if test $skip_next -eq 1",
            "      set skip_next 0",
            "      continue",
            "    end",
            "    string match -q -- '--*=*' $word; and continue",
            "    switch \"$path:$word\"",
            *_fish_path_cases(tree, value_options=True),
            "    end",
            "    switch \"$path:$word\"",
            *_fish_path_cases(tree, value_options=False),
            "    end",
            "  end",
            "  test $skip_next -eq 1; and return 1",
            "  set -l expected (string join ' ' -- $argv)",
            "  test \"$path\" = \"$expected\"",
            "end",
            "complete -c config-cli -f",
        ]
        for path, (commands, options, value_options) in sorted(tree.items()):
            condition = "__config_cli_path_is"
            if path:
                condition += " " + " ".join(shlex.quote(segment) for segment in path)
            for command in commands:
                lines.append(
                    f"complete -c config-cli -n '{condition}' -a {shlex.quote(command)}"
                )
            for option in options:
                flag = "-l " + option[2:] if option.startswith("--") else "-s " + option[1:]
                requires_value = " -r" if option in value_options else ""
                lines.append(
                    f"complete -c config-cli -n '{condition}' {flag}{requires_value}"
                )
        return "\n".join(lines) + "\n"
    raise ValueError(f"unsupported shell: {shell}")
